#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_inactive_separator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode_symbols = false

    vimcompatible = false
    windows_smartclose = 'Q'

    # bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'

[[layers]]
  name = 'autocomplete'

[[layers]]
  name = 'checkers'

[[layers]]
  name = 'shell'
  default_position = 'right'

[[layers]]
  name = 'colorscheme'

[[layers]]
  name = 'default'

[[layers]]
  name = 'git'

[[layers]]
  name = 'test'
  [layers.override_config]
    python_runner = 'pytest'

[[layers]]
  name = 'incsearch'

[[layers]]
  name = 'indentmove'

[[layers]]
  name = 'lang#python'

[[layers]]
  name = 'lang#ruby'

[[layers]]
  name = 'fzf'

[[layers]]
  name = 'operator'
